server:
  port: 8084
  servlet:
    context-path: '/ead-notification/'

spring:
  application:
    name: ead-notification-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-notification-v2
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual.creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: ${RABBITMQ_HOST:xxxx}

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost